---
  - name: Create new droplet
    digital_ocean:
      state: present
      command: droplet
      name: main
      size_id: 1gb
      region_id: nyc3
      image_id: ubuntu-16-04-x64
      wait_timeout: 500
      ssh_key_ids: "{{ ssh_id }}"
      api_token: "{{ do_token }}"
    register: new_droplet

  - name: make inventory file present
    copy:
      content: ""
      dest: "{{playbook_dir}}/inventory"
      force: yes
      mode: 0755

  - name: set inventory file
    lineinfile:
      path: "{{playbook_dir}}/inventory"
      line: "[main]\nmain ansible_host={{ new_droplet.droplet.ip_address }} ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa\n"

  - name: Wait for SSH connection
    local_action: wait_for host={{ new_droplet.droplet.ip_address }} port=22 delay=60 timeout=320 state=started
...
