---
  - name: Install python
    raw: sudo apt-get update && sudo apt-get -y install python > /dev/null 2>&1

  - name: Get nodejs package
    shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

  # Update apt-get to have mongodb package
  - name: update apt-get
    become: yes
    apt: update_cache=yes

  - name: Install apt packages
    become: yes
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items: "{{ packages }}"
...
