---
  - name: Create new droplet
    digital_ocean:
      state: present
      command: droplet
      name: proxy
      size_id: 1gb
      region_id: nyc3
      image_id: ubuntu-16-04-x64
      wait_timeout: 500
      ssh_key_ids: "{{ ssh_id }}"
      api_token: "{{ do_token }}"
    register: new_droplet

  - name: Wait for SSH connection
    local_action: wait_for host={{ new_droplet.droplet.ip_address }} port=22 delay=60 timeout=320 state=started
...
