---
    - name: Copy redis master config
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 777
      with_items:
      - src:  redis_master.conf
        dest: /etc/redis/redis.conf
      when: inventory_hostname == "proxy"

    - name: Copy redis slave conf
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 777
      with_items:
      - src:  redis_slave.conf
        dest: /etc/redis/redis.conf
      when: inventory_hostname == "police"

    - name: Add master redis ip
      lineinfile:
        path: /etc/redis/redis.conf
        line: 'slaveof {{ hostvars["proxy"].ansible_host }} 6379'
      when: inventory_hostname == "police"

    - name: Restart redis-server
      become: yes
      service:
        name: redis-server
        state: restarted
...
